# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # SSL/TLS kullanmayacağımız için devre dışı bırakıyoruz.
  sslmode: disable
  # Bağlantı havuzu büyüklüğü
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  # PostgreSQL sunucusunun konumu (WSL'de localhost veya 127.0.0.1)
  host: 127.0.0.1 
  port: 5432 # Varsayılan PostgreSQL portu
  
  # PostgreSQL süper kullanıcı adını kullanıyoruz
  username: postgres
  # PostgreSQL süper kullanıcının şifresi
  password: '1234'

development:
  <<: *default
  database: sdp_platform_api_development
  
test:
  <<: *default
  database: sdp_platform_api_test

# Veritabanına Production (Canlı) ortamında nasıl bağlanılacağı
production:
  <<: *default
  database: sdp_platform_api_production
  # Production ortamında şifre ve kullanıcı adı için mutlaka environment değişkenleri kullanılmalıdır.
  username: <%= ENV["SDP_DATABASE_USERNAME"] %>
  password: <%= ENV["SDP_DATABASE_PASSWORD"] %>
  host: <%= ENV["SDP_DATABASE_HOST"] %>